### ISSUE TITLE
Download the Raw Data

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/AIS#1]
Please download the AIS data based on the AIS assigned in TOR https://docs.google.com/spreadsheets/d/18woWQtzVmdPEKfqFsrVbj3NZ0otUdikw_0PTGexUHUM/edit#gid=0 

- The data could be downloaded from https://dhsprogram.com/data/available-datasets.cfm
- Please use the username and password provided by the World Bank team to download the raw data. 
- The raw data should be saved in the folder: https://1drv.ms/u/s!Asjjf4e9y-vXtB0oC9mFFdAetCwO?e=LUHp50
- Please use the renaming rules when saving the raw data from DHS website to the AIS folder.

**Comment by robin-wang** [comment]
@wengxyu1030 @
Downloaded. Pending OneDrive space release. Upload on hold.
- Uganda 07-08 seems to be unavailable from site.

**Comment by robin-wang** [comment]
@wengxyu1030 Upload completed. Ready to close issue, subject to your review.

**Comment by wengxyu1030** [comment]
Thanks, I am closing this issue as the data download is completed with the note that one survey Uganda 07-08 is not available on the DHS website yet.
