### ISSUE TITLE
Cote d'Ivoire2005

### ISSUE THREAD

**Issue by robin-wang** [wengxyu1030/AIS#3]
WORKFLOW DOC

{FOR REVIEWERS}
- [x] They can run the code smoothly on the reviewer's end, where the microdata could be generated without error
- [x] Review and validate the quality checking output

{FOR CODERS}
A. General Procedural Steps

- [x] Rebase current branch based on Master, ensure your branch is the latest.
Tutorial: Rebasing your project branch onto another branch
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/syncing-your-branch#rebasing-your-project-branch-onto-another-branch

- [x] Run script without error
- [x] Pass internal quality checking (the embedded quality check result: successfully produced value for the indicators and check if there're flags that the indicator value produced is too off from the published data) 

- [x] Document as comments any notable changes/caveats (if any)
- [x] When Fully Completed Survey Edits, proceed to record hours worked: https://forms.gle/tLh7fxCMMsLobGHA6

B. Checklist and Guidance

- [x] ANC
  - Skill providers
    -  Checked in the regular express section in Programs 
        - _doctor, nurse/midwife, trained birth att., trad.birth attendant_
  - Tetanus Injection: _not available_
    -  Number of Injection Before/During Pregnancy
    -  Recall period for last injection
    -  Relevant data comes other sections
  - Blood Pressure / Blood Sample / Urine Sample: _not available_
    -  Samples (m42c/d/e) are sub-questions for "receive antenatal care" in questionnaire or not

- [x] Delivery Care
  - c_facdel /  delivery institutions  / c_hospdel / delivery institutions
    -  Consistent with the regular expression section in Programs 
        - _"govt. hospital", "govt. health center, mch", "maternity", "private hosp/clinic _
  - c_skin2ski: _not available_
    -  Check if available; if, then note which variable
  - m15 skip condition
    -  Usually delivery location is a filter question for c_caesarean(m17) / stay(m61) / mother or child PNC; is it m15, if not which one, and list the conditions used for m15  if pattern is peculiar (normally (m15 = 11, 12 etc))
       - _checked the survey questionnaire, p.244 212E, m15 is not a skip condition to any of the questions (at least according to the original survey)_

- [x] PNC: _not available_
  - child pnc
    -  See if child pnc is only avaliable when (m15=11,12,96) or (m15!=11,12,96)
    -  Check if Child PNC is designed to be from full sample, i.e not a subquestion within fertility section. If a subquestion, don't generate c_pnc_any and c_pnc_eff
   
- [x] Child Vaccination (search receive/month in birth.dta. if unknown vaccine pops up, search definition in DHS report): _not available_
  - BCG
  - DTP/DPT, DTaP, DTwP or pentavalent 1-3 against diphtheria, tetanus and pertussis
  - Polio 1-3 (IPV, OPV)
  - Measles/MMR
  - Other vaccines, if any,

- [x] Child Illness: _none is available_
  - 20210510 For Providers, focus on the skilled providers rather than all
  - Diarrhea treatment provider
  - Check provider list being consistent with existing list (if not make changes in program)
  - Fever/Ari1/Ari2 treatment provider
  - Provider list being consistent with existing list
  - Fever/Fever Treatment/Cough/Cough Treatment from Full Sample
  - c_diarrhea_med, medicine and formal meds to treat are survey-specific. 20210510 focus on special medicines
  - c_diarrhea_medfor, medicine and formal meds to treat are survey-specific. 20210510 focus on special medicines
  - Validate c_ari can be generated or not

- [x] Child Mortality
  - General Observations: _need more explanation about which information to list here_

- [x] Sleeping Under Bednet
  - Adhere to program's logic, but please list any specific bednet related observations (tricky cases for presumed treated or the like)
    - _replaced ml0 by ml101 to generate this variable. 0 = no bendnet, 1= only treated bednets, 2 = only untreated bednets._ 

- [x] Child Anthropometrics
  - General Observations (No need to generate "Wasting")

- [x] Reproductive Health
  - Contraceptive, check modern methods: _c_CPR not available_
  - In Need - most updated version of logics in program (temporarily no actions needed)

- [x] Female Anthropometrics and Cancer Screening: _not available in any datasets_	
  - Mammogram (X-ray, mamm...)
  - Pap Smear (Cervical vaginal cytology)
  - Note recall indicators for Mamm or Pap Smear (for example, s1012n used as filter for s1012m)

- [x] Hospitalisation, NCD & HIV
  - Hospitalisation, general observations: _not available in any datasets_			
  - Hypertension treatment , blood pressure measure in the past or during the survey, for example check hm.dta/ind.dta/men.dta (generate a_bp_treat a_bp_sys a_bp_dial a_bp_meas a_hi_bp140 a_hi_bp140_or_on_med from ind.dta & men.dta by combining them): _not available in any of these datasets_

    - Note from WB team for reference: "don't worry if you cannot find men.dta, not all surveys have it. if it is collected from ind.dta and men.dta seperately (some survey have female & male questionnarie, collecting these data seperately), you will need to combine these 2 dataset, generating these indicators and merge them back to hm.dta. If only from ind.dta or men.dta, i.e. only for female or male, don't generate these variables. If a new/survey-specific datafile occurs, it is highly likely that it contains info. for 13.do.  "
    
  - Diabetes treatment/measure in the past (for example, a_diab_treat): _not available_
  - HIV, general observations
    - HIV questionnaire might exsit in Section 4 of "HEALTH ISSUES QUESTIONNAIRE". If they don't ask hiv test results, they are not helpful. but please document these observations.
       - _hiv03 is available: 0 = hiv negative, 1 = hiv positive, 2 = indeterminant._ 

- [ ] Cross-validate statistics in survey report, if applicable.
    - _Cross-validation not done as the report is in French._ 

- [x] Reference the NAME-SURVEY branch when your edits are finalised.
   - Refer to the github working branch created for [Name-SurveyName]

- [x] Update micro data in Onedrive

- [x] Examine Quality Checking Output Files
  - [x] Successfully produced the indicators
  - [x] Check if there's a flag that the indicator value produced is too off from the published data
       - _c_ITN, c_anc, c_anc_ski, c_sba have flags with DHS data_

**Comment by robin-wang** [comment]
@yining-sun 
Child Mortality: just intended to invite your thoughts on possibly anything unusual
Bednet: good catch
HIV：copy. if anything on HIV appears strange or worth some comments, please let me know.

Last point: Report in French, please indicate if you need assistance on that one. Cheers! 


@wengxyu1030 @yuqiliao Documentation/Checklist checked. No need to redo this bit for Cote d'Ivoire.

**Comment by wengxyu1030** [comment]
The quality checking result is as below: 
![image](https://user-images.githubusercontent.com/63058112/120287110-efd73300-c28c-11eb-86ca-3cd134eb4402.png)

The flags might contribute to the different assumptions/definitions between DHS and HEFPI indicators. (sample size issue is consolidated)

**Comment by robin-wang** [comment]
> The quality checking result is as below:
> ![image](https://user-images.githubusercontent.com/63058112/120287110-efd73300-c28c-11eb-86ca-3cd134eb4402.png)
> 
> The flags might contribute to the different assumptions/definitions between DHS and HEFPI indicators. (sample size issue is consolidated)

Noted with thanks!
